### ISSUE TITLE
Closing checklist webpage

### ISSUE THREAD

**Issue by cfarm** [cfpb/owning-a-home#438]
We currently provide a [Closing Checklist PDF](http://www.consumerfinance.gov/owning-a-home/resources/checklist_mortgage_closing.pdf) for download.

We'd like to create a design and functional prototype that converts this PDF into a webpage, which would live at http://www.consumerfinance.gov/owning-a-home/closing-checklist/ or a similar URL inside the Owning a Home project.

Steps for getting this done might be:
* [ ] Create a page template in Owning a Home and add the PDF content
* [ ] Determine which layout styles to use for this page: likely similar to the [Loan Options page] layout, or using [Capital Framework](http://cfpb.github.io/cf-layout/docs/) [Further Capital Framework layout documentation](https://github.com/cfpb/cf-layout)
* [ ] Add checklist form functionality - likely using [React](https://github.com/cfpb/owning-a-home/pull/434)
